console.log("Welcome to my channel:)");
var a = 5;
var b = 6;
var name = "Raj";
var c = a + b;
var d = "100";
var e = a + name;
var f = a * name;
var g = a + d;
var h = a * d;
var rate;
console.log(c);
console.log(typeof c);
console.log(e);
console.log(typeof e);
console.log(g);
console.log(typeof g);
console.log(f);
console.log(typeof f);
console.log(h);
console.log(typeof h);
console.log(rate);